version: 1
environments:
  staging:
    slack_channel: "#casantris-staging-alerts"
    pagerduty_service: "none"
    routing_rules:
      - when: "severity in ['warning','critical']"
        route_to: "slack"
  pre-prod:
    slack_channel: "#casantris-preprod-alerts"
    pagerduty_service: "casantris-preprod"
    routing_rules:
      - when: "severity == 'critical'"
        route_to: "pagerduty"
      - when: "severity == 'warning'"
        route_to: "slack"
  prod:
    slack_channel: "#casantris-prod-alerts"
    pagerduty_service: "casantris-prod"
    routing_rules:
      - when: "severity == 'critical'"
        route_to: "pagerduty"
      - when: "severity == 'warning'"
        route_to: "slack"
