"""add auth rate limit table

Revision ID: dd49746e1ddd
Revises: 0007_governance_share_notifications
Create Date: 2026-06-10 13:44:00.877613
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd49746e1ddd'
down_revision = '0007_governance_share_notifications'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
