{{- if .Values.postgres.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-postgres
  labels:
    app: {{ .Chart.Name }}-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-postgres
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-postgres
    spec:
      containers:
        - name: postgres
          image: "postgres:15-alpine"
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
            - name: POSTGRES_DB
              value: "casantris"
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
        {{- if .Values.pgbouncer.enabled }}
        - name: pgbouncer
          image: "edoburu/pgbouncer:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.pgbouncer.port }}
          env:
            - name: DATABASE_URL
              value: "postgresql://postgres:postgres@127.0.0.1:5432/casantris"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASSWORD
              value: "postgres"
            - name: DB_HOST
              value: "127.0.0.1"
            - name: DB_PORT
              value: "5432"
            - name: POOL_MODE
              value: {{ .Values.pgbouncer.poolMode | quote }}
            - name: MAX_CLIENT_CONN
              value: {{ .Values.pgbouncer.maxClientConn | quote }}
            - name: DEFAULT_POOL_SIZE
              value: {{ .Values.pgbouncer.defaultPoolSize | quote }}
        {{- end }}
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: {{ .Chart.Name }}-postgres-pvc
{{- end }}
